services:
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_dopaming
    restart: always # 컨테이너가 중단되었을 때 자동으로 재시작
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_PROFILES_ACTIVE: docker  # 도커 환경

    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network_dopaming
    healthcheck: # 컨테이너 상태 확인
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot
  springboot:
    build: .
    container_name: spring_boot_dopaming
    restart: always
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - network_dopaming

networks:
  network_dopaming:
    driver: bridge

volumes:
  mysql_data:
